version: "3"

volumes:
  mysql-volume:

services:
  bus_mysql:
    container_name: bus_mysql
    image: arm64v8/mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD=busdb
      - CHARACTER_SET_SERVER=utf8%
      - MYSQL_DATABASE=bus
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - mysql-volume:/var/lib/${MYSQL_DATABASE}
    ports:
      - "3308:3306"