version: "3"

services:
  bus_mysql:
    container_name: bus_mysql
    image: arm64v8/mysql:8.0.30
    env_file:
      - .env
    environment:
      - CHARACTER_SET_SERVER=utf8%
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - bus_mysql:/var/lib/${DB_NAME}
    ports:
      - "${DB_PORT}:3306"

  main-server:
    container_name: gin_backend
    build:
      context: ./main-server
      dockerfile: Dockerfile
    env_file:
      - .env
    image: main-server
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - bus_mysql

  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELASTIC_VERSION: 8.5.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - bus_elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - .env
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    restart: unless-stopped

  kibana:
    build:
      context: ./kibana
      args:
        ELASTIC_VERSION: 8.5.2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: changeme
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  bus_mysql:
  bus_elasticsearch: