version: "3"

services:
  bus_mysql:
    container_name: bus_mysql
    image: arm64v8/mysql:8.0.30
    env_file:
      - .env
    environment:
      - CHARACTER_SET_SERVER=utf8%
      - DE_NAME=${DB_NAME}
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - bus_mysql:/var/lib/${DB_NAME}
    ports:
      - "3306:3306"

  gin_backend:
    container_name: gin_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: gin_backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - bus_mysql

volumes:
  bus_mysql: