basePath: /api/v1
host: oridongnaeganayo.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  title: 우리동네가나요 API
  version: "1.0"
paths: {}
swagger: "2.0"
